### PR TITLE
Use type hints in Python; support for Souffle sum types

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
I am using typing rules for python 3.6, which is what I have on my machine.
I am not 100% sure whether they are compatible with later versions of Python. I really hope they are.

**Comment by ryzhyk** [comment]
Looks good, but the `adt_enum` test that this PR enables is failing: https://gitlab.com/ddlog/differential-datalog-mbudiu/-/pipelines/209024573

**Comment by mbudiu-vmw** [comment]
Used to work earlier, I will fix it tomorrow

**Comment by mbudiu-vmw** [comment]
Pushed a fix.

**Pull request merged**
