### PR TITLE
compile on windows

### PR DESCRIPTION
**Pull request by d4hines**
This PR is NOT a real PR!

Per #640, I just want you guys to be able to see the changes I needed to make to get DDLog to compile and run natively on Windows.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Ideally the pieces you deleted would only be conditionally compiled.
For the CLI it shouldn't be too hard to write a portable version; that piece is important.
But @ryzhyk should really review this.

**Comment by ryzhyk** [comment]
It seems that the three pieces that don't work on Windows are:
1. OVSDB bindings
2. libtool stuff
3. CLI

The first two can be excluded using Rust's and cargo's platform-specific compilation. I agree with Mihai, we need to fix the CLI to be platform-independent.

**Comment by ryzhyk** [comment]
Oh, and there's also some Unix stuff in api.rs.

**Comment by ryzhyk** [comment]
I'll start making those changes.

**Pull request closed without merging**
