### PR TITLE
Use GCC-like error message format that Emacs can parse.

### PR DESCRIPTION
**Pull request by blp**
This isn't right, because I couldn't figure out how to do the equivalent of "fprintf(stderr, ...); exit(1);" in Haskell, but it's a start.

### CODE REVIEW

**Review by mbudiu-vmw — APPROVED** [review]
I think you will need to rerun some tests and regenerate their expected outputs. Look for the tests with "fail" in test.sh

**Comment by blp** [comment]
> I think you will need to rerun some tests and regenerate their expected outputs. Look for the tests with "fail" in test.sh

I'm sure that's true, but it's it's not ready yet; I don't know how to do it right.

**Comment by ryzhyk** [comment]
I got rid of the `ddlog:` prefix. 

@blp, can you confirm that emacs like the error messages now?

**Comment by blp** [comment]
> I got rid of the `ddlog:` prefix.
> 
> @blp, can you confirm that emacs like the error messages now?

Yes, it does.

I still see the ddlog prefix and it's the error prefix that seems to have gone away, but Emacs is happy:

```
ddlog: /home/bpfaff/nicira/ovn/northd/lswitch.dl:49.1-49.18: Unknown relation 'Warning'
```

**Comment by ryzhyk** [comment]
> > I got rid of the `ddlog:` prefix.
> > @blp, can you confirm that emacs like the error messages now?
> 
> Yes, it does.
> 
> I still see the ddlog prefix and it's the error prefix that seems to have gone away, but Emacs is happy:
> 
> ```
> ddlog: /home/bpfaff/nicira/ovn/northd/lswitch.dl:49.1-49.18: Unknown relation 'Warning'
> ```

Right, there are several classes of errors. I only fixed one of them. Let me work on the other two.

**Pull request merged**
