### PR TITLE
group by implementation

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
We still don't have 'having' yet.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
@lalithsuresh : one more small step for humanity

**Comment by mbudiu-vmw** [comment]
Turns out that this does not handle nulls correctly, so the PR will be amended.

**Comment by mbudiu-vmw** [comment]
@lalithsuresh : do you want to take a look?

**Comment by lalithsuresh** [comment]
Is there a test for more than one group by column/expression? All of them either do "group by column2" or "group by substr(...)".

**Comment by mbudiu-vmw** [comment]
@lalithsuresh : I have added one more test with 2 groupby keys; if this passes we'll merge and move on to `having`.

**Comment by lalithsuresh** [comment]
The test looks good Mihai. Thanks!

**Comment by mbudiu-vmw** [comment]
This pipeline has failed because of the souffle tests.
The PR for doubles blacklists the souffle test; once we merge that one this one should pass too.

**Comment by mbudiu-vmw** [comment]
Can we merge this as well?

**Pull request closed without merging**
