### PR TITLE
start channel api

### PR DESCRIPTION
**Pull request by remysucre**

### CODE REVIEW

**Comment by remysucre** [comment]
> Shouldn't we use the Observer/Observable APIs?

We should! Let me change it.

**Comment by mbudiu-vmw** [comment]
In that case you need at least two APIs, one for the observer, and one for the observable.
A channel may actually implement both, one at each endpoint.

**Comment by mbudiu-vmw** [comment]
http://reactivex.io/documentation/observable.html

**Comment by d-e-s-o** [comment]
Would you mind adding a summary what this Channel API is meant to be used for exactly and why it looks the way it looks (i.e., the design decision made and alternatives discarded)?

It is very hard for an interested bystander to understand its purpose otherwise or follow development in general.

**Comment by mbudiu-vmw** [comment]
The channel will be a mechanism that can connect multiple DDlog computations that run on independent machines. A channel will transport relation updates between these computations. This is still very early experimental design.

**Comment by remysucre** [comment]
Closing to refactor the API.

**Pull request closed without merging**
