### PR TITLE
Made generated code compile on WASM

### PR DESCRIPTION
**Pull request by Kixiron**
* Cleaned up `differential_datalog_test` a little bit
* Made generated code compile on WASM

### CODE REVIEW

**Comment by ryzhyk** [comment]
Looks good, except some new errors in `differential_datalog_test`: https://gitlab.com/ddlog/differential-datalog-kixiron/-/jobs/1213203299

**Comment by ryzhyk** [comment]
I think this one's still failing due to the linter.

**Comment by Kixiron** [comment]
I've been having some issues getting clippy to run locally due to [rust-clippy/#7162](https://github.com/rust-lang/rust-clippy/issues/7162) so I'm more or less flying blind

**Comment by Kixiron** [comment]
@ryzhyk fixed everything

**Pull request merged**
