### PR TITLE
Simplify Translator.compileAndLoad()

### PR DESCRIPTION
**Pull request by lalithsuresh**
The earlier version used a Classloader trick to edit the `java.library.path` variable.
This is not portable and does work across different types of JDKs (it failed on OpenJDK 12).
This fix instead invokes System.load() against the absolute path of the created library.

Invoking System.load() within compileAndLoad() is redundant with the System.loadLibrary()
attempt that is attempted in the static constructor within the DDlogAPI() class.
This works out fine if java.library.path includes the current directory.

### CODE REVIEW

**Comment by lalithsuresh** [comment]
@mbudiu-vmw sounds good. Left a comment on #581. Can we merge this PR?

**Comment by ryzhyk** [comment]
@mbudiu-vmw 
This PR broke master.

**Comment by mbudiu-vmw** [comment]
the tests seemed to have passed.

**Comment by ryzhyk** [comment]
Gitlab tests don't run on @lalithsuresh 's commits unless he starts mirroring his repo to the gitlab org.

**Comment by lalithsuresh** [comment]
I see what the bug is. Seems like the default for `java.library.path` does not include "." in your CI infrastructure. And `DDlogApi` assumes the library is available within one of the paths indicated by `java.library.path`. I've sent a fix in #589, which explicitly sets the path variable for the tests.

**Pull request merged**
