### PR TITLE
Support string comparison

### LINKED ISSUE #498: Ddlog does not support string comparisons

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Fixes #498

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
In fact, comparison can be supported for almost any DDlog type.

**Comment by mbudiu-vmw** [comment]
Pushed another commit which supports comparisons for all types.
Let me also document this.

**Comment by mbudiu-vmw** [comment]
Is this ready?

**Comment by ryzhyk** [comment]
As far as I'm concerned, yes. Can you please merge if tests are passing?

**Pull request merged**
