### PR TITLE
Fix bug; add anchor on each table row

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by ryzhyk** [comment]
@mbudiu-vmw, any progress on the issue with anchor's not working on collapsed table rows?

**Comment by mbudiu-vmw** [comment]
I believe that the solution is to actually check the url and if it contains an anchor to automatically expand the document to that path.

**Comment by mbudiu-vmw** [comment]
Would starting with all cells expanded in that case be acceptable?

**Comment by ryzhyk** [comment]
I think so.

**Comment by mbudiu-vmw** [comment]
Fixes #1124

**Pull request merged**
